### ISSUE TITLE
Redis Fails to Install on Windows 2008 R2 Standard SP1

### ISSUE THREAD

**Issue by tuldok89** [microsoftarchive/redis#404]
### System Specs
- OS: Windows 2008 R2 Standard SP1 x64
- CPU: Intel Xeon E5649
- RAM: 16GB

I was able to install this in my desktop (Windows 7 x64), but it fails on our server.

At the start of the installation, it instantly fails with the following error message.

![rediserror](https://cloud.githubusercontent.com/assets/854884/12909943/f8711de0-cf40-11e5-9db5-e8ad1159dc31.png)

I've copied MSI installation log file below...

```
=== Logging started: 2/9/2016  13:52:30 ===
Action 13:52:30: INSTALL. 
Action start 13:52:30: INSTALL.
Action 13:52:30: FindRelatedProducts. Searching for related applications
Action start 13:52:30: FindRelatedProducts.
Action ended 13:52:30: FindRelatedProducts. Return value 1.
Action 13:52:30: PrepareDlg. 
Action start 13:52:30: PrepareDlg.
Info 2898.For WixUI_Font_Normal textstyle, the system created a 'Tahoma' font, in 0 character set, of 13 pixels height.
Info 2898.For WixUI_Font_Bigger textstyle, the system created a 'Tahoma' font, in 0 character set, of 19 pixels height.
Action 13:52:30: PrepareDlg. Dialog created
Action ended 13:52:30: PrepareDlg. Return value 1.
Action 13:52:30: AppSearch. Searching for installed applications
Action start 13:52:30: AppSearch.
Action ended 13:52:30: AppSearch. Return value 0.
Action 13:52:30: WixQueryOsWellKnownSID. 
Action start 13:52:30: WixQueryOsWellKnownSID.
Action ended 13:52:30: WixQueryOsWellKnownSID. Return value 1.
Action 13:52:30: LaunchConditions. Evaluating launch conditions
Action start 13:52:30: LaunchConditions.
Action ended 13:52:30: LaunchConditions. Return value 1.
Action 13:52:30: ca_CheckIfFirewallServiceRunning. 
Action start 13:52:30: ca_CheckIfFirewallServiceRunning.
SFXCA: Extracting custom action to temporary directory: C:\Users\201200~1\AppData\Local\Temp\6\MSI2857.tmp-\
SFXCA: Binding to CLR version v2.0.50727
Calling custom action RedisMsi.CustomActions!RedisMsi.CustomActions.CustomActions.CheckIfFirewallServiceRunning
Error: could not load custom action class RedisMsi.CustomActions.CustomActions from assembly: RedisMsi.CustomActions
System.BadImageFormatException: Could not load file or assembly 'RedisMsi.CustomActions' or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded.
File name: 'RedisMsi.CustomActions'
   at System.Reflection.Assembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, Assembly locationHint, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection)
   at System.Reflection.Assembly.InternalLoad(AssemblyName assemblyRef, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.AppDomain.Load(String assemblyString)
   at Microsoft.Deployment.WindowsInstaller.CustomActionProxy.GetCustomActionMethod(Session session, String assemblyName, String className, String methodName)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value  (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value .

CustomAction ca_CheckIfFirewallServiceRunning returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 13:52:30: ca_CheckIfFirewallServiceRunning. Return value 3.
Action 13:52:30: FatalError. 
Action start 13:52:30: FatalError.
Action 13:52:30: FatalError. Dialog created
Action ended 13:52:31: FatalError. Return value 2.
Action ended 13:52:31: INSTALL. Return value 3.
Property(C): UpgradeCode = {05410198-7212-4FC4-B7C8-AFEFC3DA0FBC}
Property(C): ADD_FIREWALL_RULE = 1
Property(C): WixUIRMOption = UseRM
Property(C): WIXUI_INSTALLDIR = INSTALLFOLDER
Property(C): PORT = 6379
Property(C): MAXMEMORY = 100
Property(C): ALLUSERS = 1
Property(C): ARPNOMODIFY = 1
Property(C): ProgramFiles64Folder = C:\Program Files\
Property(C): SourceDir = C:\Users\20120000248\Desktop\
Property(C): VersionNT = 601
Property(C): ARPURLINFOABOUT = https://github.com/MSOpenTech/redis
Property(C): FIREWALL_SERVICE_STOPPED = 0
Property(C): Manufacturer = MSOpenTech
Property(C): ProductCode = {C8312FC3-8684-43D4-BB35-9C4673DD260E}
Property(C): ProductLanguage = 1033
Property(C): ProductName = Redis on Windows
Property(C): ProductVersion = 3.0.501
Property(C): DefaultUIFont = WixUI_Font_Normal
Property(C): WixUI_Mode = InstallDir
Property(C): ErrorDialog = ErrorDlg
Property(C): SecureCustomProperties = ADD_INSTALLFOLDER_TO_PATH;USE_MEMORY_LIMITS;WIX_ACCOUNT_NETWORKSERVICE;WIX_DOWNGRADE_DETECTED;WIX_UPGRADE_DETECTED
Property(C): MsiLogFileLocation = C:\Users\20120000248\log.txt
Property(C): PackageCode = {2FFF0FD6-29DE-44BC-8E7A-E6FAB68B07A2}
Property(C): ProductState = -1
Property(C): PackagecodeChanging = 1
Property(C): CURRENTDIRECTORY = C:\Users\20120000248
Property(C): CLIENTUILEVEL = 0
Property(C): CLIENTPROCESSID = 6344
Property(C): MsiSystemRebootPending = 1
Property(C): VersionDatabase = 200
Property(C): VersionMsi = 5.00
Property(C): VersionNT64 = 601
Property(C): WindowsBuild = 7601
Property(C): ServicePackLevel = 1
Property(C): ServicePackLevelMinor = 0
Property(C): MsiNTProductType = 3
Property(C): WindowsFolder = C:\Windows\
Property(C): WindowsVolume = C:\
Property(C): System64Folder = C:\Windows\system32\
Property(C): SystemFolder = C:\Windows\SysWOW64\
Property(C): RemoteAdminTS = 1
Property(C): TempFolder = C:\Users\201200~1\AppData\Local\Temp\6\
Property(C): ProgramFilesFolder = C:\Program Files (x86)\
Property(C): CommonFilesFolder = C:\Program Files (x86)\Common Files\
Property(C): CommonFiles64Folder = C:\Program Files\Common Files\
Property(C): AppDataFolder = C:\Users\20120000248\AppData\Roaming\
Property(C): FavoritesFolder = C:\Users\20120000248\Favorites\
Property(C): NetHoodFolder = C:\Users\20120000248\AppData\Roaming\Microsoft\Windows\Network Shortcuts\
Property(C): PersonalFolder = C:\Users\20120000248\Documents\
Property(C): PrintHoodFolder = C:\Users\20120000248\AppData\Roaming\Microsoft\Windows\Printer Shortcuts\
Property(C): RecentFolder = C:\Users\20120000248\AppData\Roaming\Microsoft\Windows\Recent\
Property(C): SendToFolder = C:\Users\20120000248\AppData\Roaming\Microsoft\Windows\SendTo\
Property(C): TemplateFolder = C:\ProgramData\Microsoft\Windows\Templates\
Property(C): CommonAppDataFolder = C:\ProgramData\
Property(C): LocalAppDataFolder = C:\Users\20120000248\AppData\Local\
Property(C): MyPicturesFolder = C:\Users\20120000248\Pictures\
Property(C): AdminToolsFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\
Property(C): StartupFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\
Property(C): ProgramMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\
Property(C): StartMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\
Property(C): DesktopFolder = C:\Users\Public\Desktop\
Property(C): FontsFolder = C:\Windows\Fonts\
Property(C): GPTSupport = 1
Property(C): OLEAdvtSupport = 1
Property(C): ShellAdvtSupport = 1
Property(C): MsiAMD64 = 6
Property(C): Msix64 = 6
Property(C): Intel = 6
Property(C): PhysicalMemory = 16374
Property(C): VirtualMemory = 43166
Property(C): AdminUser = 1
Property(C): MsiTrueAdminUser = 1
Property(C): LogonUser = 20120000248
Property(C): UserSID = S-1-5-21-758187812-239668402-1231754661-9472
Property(C): UserLanguageID = 1033
Property(C): ComputerName = CPH43
Property(C): SystemLanguageID = 1033
Property(C): ScreenX = 1920
Property(C): ScreenY = 1080
Property(C): CaptionHeight = 19
Property(C): BorderTop = 1
Property(C): BorderSide = 1
Property(C): TextHeight = 16
Property(C): TextInternalLeading = 3
Property(C): ColorBits = 16
Property(C): TTCSupport = 1
Property(C): Time = 13:52:31
Property(C): Date = 2/9/2016
Property(C): MsiNetAssemblySupport = 2.0.50727.4927
Property(C): MsiWin32AssemblySupport = 6.1.7601.17514
Property(C): RedirectedDllSupport = 2
Property(C): MsiRunningElevated = 1
Property(C): Privileged = 1
Property(C): USERNAME = cph
Property(C): COMPANYNAME = cph operations
Property(C): DATABASE = C:\Users\20120000248\Desktop\Redis-x64-3.0.501.msi
Property(C): OriginalDatabase = C:\Users\20120000248\Desktop\Redis-x64-3.0.501.msi
Property(C): SOURCEDIR = C:\Users\20120000248\Desktop\
Property(C): VersionHandler = 5.00
Property(C): UILevel = 5
Property(C): ACTION = INSTALL
Property(C): EXECUTEACTION = INSTALL
Property(C): WIX_ACCOUNT_LOCALSYSTEM = NT AUTHORITY\SYSTEM
Property(C): WIX_ACCOUNT_LOCALSERVICE = NT AUTHORITY\LOCAL SERVICE
Property(C): WIX_ACCOUNT_NETWORKSERVICE = NT AUTHORITY\NETWORK SERVICE
Property(C): WIX_ACCOUNT_ADMINISTRATORS = BUILTIN\Administrators
Property(C): WIX_ACCOUNT_USERS = BUILTIN\Users
Property(C): WIX_ACCOUNT_GUESTS = BUILTIN\Guests
=== Logging stopped: 2/9/2016  13:52:31 ===
MSI (c) (C8:30) [13:52:31:957]: Product: Redis on Windows -- Installation failed.

MSI (c) (C8:30) [13:52:31:957]: Windows Installer installed the product. Product Name: Redis on Windows. Product Version: 3.0.501. Product Language: 1033. Manufacturer: MSOpenTech. Installation success or error status: 1603.
`
```

**Comment by enricogior** [comment]
Hi @tuldok89 
the MSI installer needs the .Net framework 4.5 in order to do some processing, it looks like it's missing on your machine.
If you prefer not to install the .Net framework 4.5 you can use the command line options to install the service, in that case the framework is not required.

**Comment by tuldok89** [comment]
Hello @enricogior 

Thanks for the assist. Got it working now.
