### ISSUE TITLE
Unexpected reply bug

### ISSUE THREAD

**Issue by Ahmad-Hassan1511** [microsoftarchive/redis#81]
Suddenly Redis (2.4) stopped working while trying to read from it with the following error: 

ServiceStack.Redis.RedisResponseException: Unexpected reply: 9355255040794340#DevicesDataCache, sPort: 63770, LastCommand: GET 9357464036634845#DevicesDataCache
   at ServiceStack.Redis.RedisNativeClient.CreateResponseError(String error) in C:\Dan\ServiceStack.Redis\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 148
   at ServiceStack.Redis.RedisNativeClient.ReadData() in C:\Dan\ServiceStack.Redis\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 527
   at ServiceStack.Redis.RedisNativeClient.SendExpectData(Byte[][] cmdWithBinaryArgs) in C:\Dan\ServiceStack.Redis\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 302
   at ServiceStack.Redis.RedisNativeClient.GetBytes(String key) in C:\Dan\ServiceStack.Redis\src\ServiceStack.Redis\RedisNativeClient.cs:line 313
   at ServiceStack.Redis.RedisNativeClient.Get(String key) in C:\Dan\ServiceStack.Redis\src\ServiceStack.Redis\RedisNativeClient.cs:line 305
   at ServiceStack.Redis.RedisClient.GetValue(String key) in C:\Dan\ServiceStack.Redis\src\ServiceStack.Redis\RedisClient.cs:line 115
   at ServiceStack.Redis.RedisClient.Get[T](String key) in C:\Dan\ServiceStack.Redis\src\ServiceStack.Redis\RedisClient.ICacheClient.cs:line 32

**Comment by jepickett** [comment]
We have significantly improved the stability of the Windows port of Redis in 2.6.14 and 2.8.4. The 2.4 branch is not likely to get attention any time soon.
